[general]
import = ["~/.dotfiles/.config/alacritty/colors.toml", "~/.dotfiles/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.65
startup_mode = "Windowed"
blur = true

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 172
lines = 37

[window.padding]
x = 5
y = 5
